spring:
  main:
    sources: io.fabric8.component.core

camel:
  springboot:
    # The Camel context name
    name: CamelCore
    main-run-controller: true

logging:
  config: "classpath:logback.xml"
